<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Form Submission - {{ $form->name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
            margin: 40px;
        }
        .header {
            border-bottom: 3px solid #4CAF50;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        h1 {
            color: #4CAF50;
            margin: 0;
            font-size: 24px;
        }
        .submission-info {
            background-color: #f5f5f5;
            padding: 15px;
            margin-bottom: 30px;
            border-left: 4px solid #4CAF50;
        }
        .submission-info p {
            margin: 5px 0;
        }
        .field-section {
            margin-bottom: 20px;
        }
        .field-label {
            font-weight: bold;
            color: #555;
            margin-bottom: 5px;
        }
        .field-value {
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #e0e0e0;
            border-radius: 3px;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            font-size: 10px;
            color: #777;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table td {
            padding: 8px;
            border-bottom: 1px solid #e0e0e0;
        }
        table td:first-child {
            font-weight: bold;
            width: 200px;
            color: #555;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $form->name }}</h1>
        <p style="color: #777; margin: 5px 0;">Form Submission</p>
    </div>

    <div class="submission-info">
        <p><strong>Submission ID:</strong> {{ $submission->id }}</p>
        <p><strong>Submitted:</strong> {{ $submission->created_at->format('F j, Y g:i A') }}</p>
        <p><strong>IP Address:</strong> {{ $submission->ip_address }}</p>
    </div>

    <h2 style="color: #4CAF50; margin-bottom: 20px;">Submitted Information</h2>

    <table>
        @foreach($field_values as $fieldValue)
            @if($fieldValue->field && !in_array($fieldValue->field->type, ['password', 'hidden']))
                <tr>
                    <td>{{ $fieldValue->field->label ?? ucfirst($fieldValue->field->name) }}:</td>
                    <td>{{ $fieldValue->value ?? 'N/A' }}</td>
                </tr>
            @endif
        @endforeach
    </table>

    <div class="footer">
        <p>Generated by Slick Forms | {{ config('app.name') }}</p>
        <p>{{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
